<!-- script -->
<?php 
	echo $this->headScript()->appendFile(URL_SCRIPT."ckeditor/ckeditor.js","text/javascript");
?>

<!-- BUTTON-TOOL -->
<?php echo $this->render("area_button.phtml") ?>

<?php 
	$myForm = $this->myForm;
	$myForm->prepare();	
?>

<!-- ALERT -->
<?php  echo $this->flashMessenger()->render(); ?>
<div class="box box-info">
	<?php echo $myForm->showError() ?>
    <div class="box-body">
    	<?php 
    		echo $this->form()->openTag($myForm);
	    		echo $this->partialLoop("partial_formAdminGroup.phtml",array(
	    				array("elm" =>$myForm->get("username")),
	    				array("elm" =>$myForm->get("fullname")),
	    				array("elm" =>$myForm->get("email")),
	    				array("elm" =>$myForm->get("password")),
	    				array("elm" =>$myForm->get("group")),
	    				array("elm" =>$myForm->get("image")),
	    				array("elm" =>$myForm->get("avatar"),"type"=>"avatar"),
	    				array("elm" =>$myForm->get("ordering")),
	    				array("elm" =>$myForm->get("status")),
	    				array("elm" =>$myForm->get("sign")),
	    				array("elm" =>$myForm->get("id"),"type"=>"hidden"),
	    				array("elm" =>$myForm->get("action"),"type"=>"hidden"),
	    				array("elm" =>$myForm->get("avatar"),"type"=>"hidden"),
	    				
	    			));
    		echo $this->form()->closeTag();
    	?>
    </div>
</div>

<script type="text/javascript">
	CKEDITOR.replace('sign',{ 
        	customConfig : "custom/config_1.js",
    });
</script>