<!-- BUTTON-TOOL -->
<?php echo $this->render("area_button.phtml") ?>

<?php 
	$myForm = $this->myForm;
	$myForm->prepare();	
?>
<div class="box box-info">
	<?php echo $myForm->showError() ?>
    <div class="box-body">
    	<?php 
    		echo $this->form()->openTag($myForm);
	    		echo $this->partialLoop("partial_formAdminGroup.phtml",array(
	    				array("elm" =>$myForm->get("name")),
	    				array("elm" =>$myForm->get("ordering")),
	    				array("elm" =>$myForm->get("status")),
	    			));
	    		echo $this->formHidden($myForm->get("id"));
    		echo $this->form()->closeTag();
    	?>
    </div>
</div>