<?php


//DATA LIST-ITEM
  $xhtmlTable = 'Không có dữ liệu ';
  if(isset($this->items) && !empty($this->items)){
    $xhtmlTable = "";
    foreach($items as $item){
        $class = $this->cycle(array("odd","even"))->next();
        $name  = $item->name;
        $created = date("H:i:s d-m-Y",strtotime($item->created));
        $created_by = $item->created_by;
        $order = $item->ordering;
        $status = ($item->status == 1)? "success" : "default";
        $id = $item->id;
        $xhtmlTable .= sprintf('<tr class="%s">
                              <td class="sorting_1"><input type="checkbox" /></td>
                              <td>%s</td><td>%s</td><td>%s</td><td><input class="input-order" size="4" type="text" value="%s"/></td>
                              <td><a href="#" class="label label-%s"><i class="fa fa-check"></i></a></td>
                              <td>%s</td>
                        </tr>',$class,$name,$created,$created_by,$order,$status,$id);
    }
  }
// LINK FORM
  $linkForm = $this->basePath("admin/group/filter");
// SELECT-BOX
/*
<select size="1" name="example1_length" class="input-sm">
                        <option value="10" selected="selected">Select a status</option>
                        <option value="25">25</option>
                      </select>
 */
 
?>

<div class="row">
          <!-- BUTTON -->
            <div class="text-center">
              <a class="btn btn-app"><i class="fa fa-repeat"></i> Reload</a>
              <a class="btn btn-app"><i class="fa fa-plus-square-o"></i> Add</a>
              <a class="btn btn-app"> <i class="fa fa-check-circle-o"></i> Publish</a>
              <a class="btn btn-app"><i class="fa fa-circle-o"></i> Unpublish</a>
              <a class="btn btn-app"><i class="fa fa-minus-circle"></i> Delete</a>  </div><!-- /.box-body -->
<!-- ALERT -->
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4>  <i class="icon fa fa-check"></i> Alert!</h4>
                Success alert preview. This alert is dismissable.</div>
<!-- END_ALERT -->

<!-- TABLE -->
<form name="adminForm" id="adminForm" action="<?php echo $linkForm ?>" method="post">
      <div class="box box-info">
          <div class="box-body">
            <div class="box-header" style="padding-top: 10px;">
                  <!-- SEARCH BOX -->
                  <div class="col-xs-4">
                    <div class="dataTables_filter" id="example1_filter" style="float: left;">
                      <div class="input-group input-group-sm">
                          <div class="input-group-btn">
                              <button type="button" data-toggle="dropdown" class="btn btn-sm btn-default dropdown-toggle">Search by Name</button>
                              <ul class="dropdown-menu">
                                  <li><a href="#">Search by Name</a></li>
                                  <li><a href="#">Search by Email</a></li>
                                  <li><a href="#">Search by All</a></li>
                              </ul>
                          </div>
                          <input type="text" class="form-control input-sm col-xs-2">
                          <span class="input-group-btn">
                            <button class="btn btn-default btn-flat" type="button">Clear</button>
                              <button class="btn btn-primary btn-flat" type="button">Go!</button>
                          </span>
                      </div>
                    </div>
                  </div>
                  <!-- SELECT BOX -->
                  <div class="col-xs-8 ">
                    <div class="dataTables_filter pull-right">
                      <?php
                        echo $this->cmsSelectBox("filter_status","-- Select a status--",array("active"=>"Active","inactive"=>"InActive"),null);
                      ?>
                    </div>
                  </div>
            </div>

            <div class="row"><div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable text-center" role="grid" aria-describedby="example1_info">
                    <thead>
                      <tr role="row">
                        <th class="text-center">
                           <button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>
                        </th>
                        <?php echo $this->changeSortLink($this->ssOrder,"name","Name"); ?>
                        <?php echo $this->changeSortLink($this->ssOrder,"created","Created"); ?>
                        <?php echo $this->changeSortLink($this->ssOrder,"created_by","Created_by"); ?>
                        <?php echo $this->changeSortLink($this->ssOrder,"ordering","Ordering"); ?>
                        <?php echo $this->changeSortLink($this->ssOrder,"status","Status"); ?>
                        <?php echo $this->changeSortLink($this->ssOrder,"id","ID"); ?>
                        <input type="hidden" name="order" value="ASC">
                        <input type="hidden" name="order_by" value="id">
                      </tr>
                    </thead>
                    <tbody>
                     <?php echo $xhtmlTable ?>
                    </tbody>
                </table>
            </div></div>
            <div class="row">
            <?php
              $realURL = $this->url("adminRoute/paginator",array("controller"=>"group"));
              echo $this->paginationControl($this->paginator,null,"paginator.phtml",array("realURL"=>$realURL));
            ?>
            </div>
          </div>
      </div>
</form>
</div>