<?php

use Zend\Form\Element\Text;
use Zend\Form\Element\Url;
$currentController = $this->paramSetting["controller"];
//DATA LIST-ITEM
  $xhtmlTable = 'Không có dữ liệu ';
  if(isset($this->items) && !empty($this->items)){
    $xhtmlTable = "";
    foreach($items as $item){
        $class      = $this->cycle(array("odd","even"))->next();
        $name       = $item->name;
        $created    = date("H:i:s d-m-Y",strtotime($item->created));
        $created_by = $item->created_by;
        $id         = $item->id;
        $ordering   = $this->zvnFormText("ordering[{$id}]",$item->ordering,array("class"=>"input-order","size"=>"4"));
        $status     = $this->changeStatusLink($id,$item->status);
        $linkEdit   = $this->linkToGo("adminRoute/default",array("controller"=>"group",
                                                            "action"    =>"edit",
                                                            "id"        =>$id         
                                                      ));
        $xhtmlTable .= '<tr class="'.$class.'">
                              <td class="sorting_1"><input type="checkbox" class="check-box" name="id[]" value="'.$id.'" /></td>
                              <td><a href="'.$linkEdit.'">'.$name.'</a></td>
                              <td>'.$created.'</td>
                              <td>'.$created_by.'</td>
                              <td>'.$ordering.'</td>
                              '.$status.' 
                              <td>'.$id.'</td>
                        </tr>'; 
    }
  }
// LINK FORM
$linkForm = $this->basePath("admin/group/filter");
// SEARCH FUNC [SELECT-BOX]
$value = array(
    "name" => "Search by Name",
    "id"   => "Search by ID",
    "all"  => "Search All"
);
$search       = $this->paramSetting['search'];
$keyword_type = $this->zvnFormSelectBox("search_key",null,$value,$search['search_key']);
$keyword_text = $this->zvnFormText("search_value",$search['search_value'],array("class"=>"form-control input-sm "));
$btn_claer    = $this->zvnFormButton("btn_clear","clear","Clear",array("type"=>"submit"));
$btn_go       = $this->zvnFormButton("btn_go",null,"Go!",array("class"=>"btn-primary","type"=>"submit"));

?>

<div class="row">
          <!-- BUTTON -->
            <div class="text-center">
              <a class="btn btn-app btn-status"  onclick="submitForm('/admin/group/ordering')"><i class="fa fa-repeat"></i> Reload</a>
              <a class="btn btn-app " href="/admin/group/add"><i class="fa fa-plus-square-o"></i> Add</a>
              <a class="btn btn-app btn-status"  onclick="changeMultiStatus(1)"><i class="fa fa-check-circle-o"></i> Active</a>
              <a class="btn btn-app btn-status"  onclick="changeMultiStatus(0)"><i class="fa fa-circle-o"></i> InActive</a>
              <a class="btn btn-app btn-status"  onclick="deleteMulti()"><i class="fa fa-minus-circle"></i> Delete</a>  </div><!-- /.box-body -->
<!-- ALERT -->
            <?php  echo $this->flashMessenger()->render(); ?>
<!-- END_ALERT -->

<!-- TABLE -->
<form name="adminForm" id="adminForm" action="<?php echo $linkForm ?>" method="post">
      <div class="box box-info">
          <div class="box-body">
            <div class="box-header" style="padding-top: 10px;">
                  <!-- SEARCH BOX -->
                    <?php 
                      echo $this->partial("partial_search.phtml",array(
                          "keyword_type" => $keyword_type,
                          "keyword_text" => $keyword_text,
                          "button"       => $btn_claer.$btn_go
                      ))
                    ?>
                  <!-- SELECT BOX -->
                  <div class="col-xs-8 ">
                    <div class="dataTables_filter pull-right">
                      <?php
                        $filter_status = $this->paramSetting['filter_status'];
                        echo $this->zvnFormSelectBox("filter_status","-- Select a status--",array("active"=>"Active","inactive"=>"InActive"),$filter_status);
                      ?>
                    </div>
                  </div>
            </div>

            <div class="row"><div class="col-sm-12">
                <!-- ORDER -->
                <table id="example2" class="table table-bordered table-hover dataTable text-center" >
                    <thead>
                      <tr role="row">
                        <th class="text-center">
                           <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>
                        </th>
                        <?php 
                            //-----order---
                            $order = $this->paramSetting['order'];
                            echo $this->changeSortLink($order,"name","Name").
                                 $this->changeSortLink($order,"created","Created").
                                 $this->changeSortLink($order,"created_by","Created_by").
                                 $this->changeSortLink($order,"ordering","Ordering").
                                 $this->changeSortLink($order,"status","Status").
                                 $this->changeSortLink($order,"id","ID");   

                         ?>
                      </tr>
                      <?php
                      //----hidden---
                            echo $this->zvnFormHidden("order","ASC").
                                 $this->zvnFormHidden("order_by","id").
                                 $this->zvnFormHidden("status","").
                                 $this->zvnFormHidden("id","");
                      ?>
                    </thead>
                    <tbody>
                     <?php echo $xhtmlTable ?>
                    </tbody>
                </table>
            </div></div>
            <div class="row">
            <?php
              $realURL = $this->linkToGo("adminRoute/paginator",array("controller"=>"group"));
              echo $this->paginationControl($this->paginator,null,"paginator.phtml",array("realURL"=>$realURL));
            ?>
            </div>
          </div>
      </div>
</form>
</div>