<?php 
$bookInfo    = $this->bookInfo;
$name        = $bookInfo->name;
$catName     = $bookInfo->cat_name;
$picture     = URL_FILES . "books/thumb/210x280/".$bookInfo->picture;
$realPrice   = $realPrice = $this->createPrice($bookInfo->price,$bookInfo->sale_off,array("task"=>"book-special"));
$description = $bookInfo->description;
$this->headTitle($name);
$urlRelated  = $this->url("shopRoute/default",array("controller"=>"book","action"=>"related"));
?>

<div class="product-info">
	<div class="row">
		<div class="col-sm-4">
			<h1 class="view"></h1>

			<div id="default_gallery" class="left spacing">
				<div class="image">
					<div  class="zoomWrapper">
						<img  src="<?php echo $picture ?>" title="<?php echo $name ?>" alt="<?php echo $name ?>" style="position: absolute;">
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-8">
			<h1><?php echo $name ?></h1>
			<div class="description">
				<div class="product-section">
					<span>Category : </span> <?php echo $catName ?><br>
				</div>
				<div class="price">
					<?php echo $realPrice ?>
				</div>
				<div class="cart">
					<div class="prod-row">
						<div class="cart-top">
							<div class="cart-top-padd form-inline">
								<label>Qty: 
									<input class="q-mini" type="text" name="quantity" value="1"> 
									<input class="q-mini" type="hidden" name="product_id" value="33">
								</label> 
								<a id="button-cart" class="button-prod"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
							</div>
							<div class="clear"></div>
						</div>
					</div>
				</div>
				<div class="clear"></div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	
	<div class="tabs">
		<div class="tab-heading">Description</div>
		<div class="tab-content">
			<?php echo $description ?>
		</div>
	</div>
	<?php 
		echo $this->zvnFormHidden("cat_id",$bookInfo->category_id);
		echo $this->zvnFormHidden("url_related",$urlRelated);
		echo $this->zvnFormHidden("book_id",$bookInfo->id);
	?>
	
	<div  id="book-related" class="box featured">
		
				<!-- Ajax -->
		
	</div>

</div>
<script type="text/javascript">
	$(document).ready(function(){
		var url    = $("input[name=url_related]").val();
		var cat_id = $("input[name=cat_id]").val();
		var b_id   = $("input[name=book_id]").val();
		$("#book-related").load(url,{category_id:cat_id,book_id:b_id});
	})
</script>