<?php 
$bookInfo    = $this->bookInfo;
$name        = $bookInfo->name;
$picture     = URL_FILES . "books/thumb/210x280/".$bookInfo->picture;
$realPrice   = $realPrice = $this->createPrice($bookInfo->price,$bookInfo->sale_off,array("task"=>"book-special"));
$description = $bookInfo->description;
?>

<div class="product-info">
	<div class="row">
		<div class="col-sm-4">
			<h1 class="view"></h1>

			<div id="default_gallery" class="left spacing">
				<div class="image">
					<div  class="zoomWrapper">
						<img  src="<?php echo $picture ?>" title="<?php echo $name ?>" alt="<?php echo $name ?>" style="position: absolute;">
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-sm-8">
			<h1><?php echo $name ?></h1>
			<div class="description">
				<div class="product-section">
					<span>Category : </span> Product 6<br>
				</div>
				<div class="price">
					<?php echo $realPrice ?>
				</div>
				<div class="cart">
					<div class="prod-row">
						<div class="cart-top">
							<div class="cart-top-padd form-inline">
								<label>Qty: 
									<input class="q-mini" type="text" name="quantity" value="1"> 
									<input class="q-mini" type="hidden" name="product_id" value="33">
								</label> 
								<a id="button-cart" class="button-prod"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
							</div>
							<div class="extra-button">
								<div class="wishlist">
									<a onclick="addToWishList('33');" title="Add to Wish List"><i class="fa fa-star"></i><span>Add to Wish List</span></a>
								</div>
								<div class="compare">
									<a onclick="addToCompare('33');" title="Add to Compare"><i class="fa fa-bar-chart-o"></i><span>Add to Compare</span></a>
								</div>
							</div>
							<div class="clear"></div>
						</div>
					</div>
				</div>
				<div class="clear"></div>
				<div class="review">
					<div>
						<img src="<?php echo URL_IMG_SHOP ?>stars-0.png" alt="0 reviews">&nbsp;&nbsp;
						<div class="btn-rew">
							<a onclick="document.getElementById('tab-review').scrollIntoView();">0 reviews</a> 
							<a onclick="document.getElementById('tab-review').scrollIntoView();"><i class="fa fa-pencil"></i>Write a review</a>
							<div class="clear"></div>
						</div>
					</div>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	
	<div class="tabs">
		<div class="tab-heading">Description</div>
		<div class="tab-content">
			<?php echo $description ?>
		</div>
	</div>
	
	<div class="tabs" id="tab-review">
		<div class="tab-heading">Reviews (0)</div>
		<div class="tab-content">
			<div id="review">
				<div class="content">There are no reviews for this product.</div>
			</div>
			<h2 id="review-title">Write a review</h2>
			<label>Your Name:</label> <input type="text" name="name" value=""> <br><br> 
			<label>Your Review:</label><textarea name="text" cols="40" rows="8" style="width: 93%;"></textarea>
			<div class="clear"></div>
			
			<span style="font-size: 11px;">
				<span style="color: #FF0000;">Note:</span>
				HTML is not translated!
			</span><br> <br> 
			<label class="inline">Rating:</label>
			<div class="form-inline border">
				<span class="radio">Bad</span>&nbsp; 
				<input type="radio" name="rating" value="1"> &nbsp; 
				<input type="radio" name="rating" value="2"> &nbsp; 
				<input type="radio" name="rating" value="3"> &nbsp; 
				<input type="radio" name="rating" value="4"> &nbsp; 
				<input type="radio" name="rating" value="5"> &nbsp; 
				<span class="radio">Good</span><br>
			</div>

			<label>Enter the code in the box below:</label> 
			<input type="text" name="captcha" value=""> 
			<img src="" alt="" id="captcha"> <br>
			<div class="buttons">
				<div>
					<a id="button-review" class="button-cont-right">Continue<i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
		</div>
	</div>

</div>