<?php 

	$categoryItem = $this->categoryItem;
	$this->headTitle($categoryItem->name);
	$linkGrid = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>"grid"));
	$linkList = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>"list"));
	
?>
<!-- BREADCRUMB -->
<div class="breadcrumb">
	<?php echo $this->createBreadcrumb($listBreadcumb); ?>
</div>

<!-- CATEGORY NAME -->
<h1 class="style-1"><?php echo $categoryItem->name ?></h1>

<!-- CATEGORY INFO -->
<div class="category-info">
	<?php echo $categoryItem->description ?>
</div>

<!-- PRODUCT FILTER -->
<div class="product-filter">
	<div class="sort">
		<b>Sort By:</b> <select onchange="location = this.value;">
			<option value="1" selected="selected">Default</option>
			<option value="1">Name (A - Z)</option>
			<option value="1">Name (Z - A)</option>
		</select>
	</div>

	<div class="limit">
		<b>Show:</b> <select onchange="location = this.value;">
			<option value="1" selected="selected">6</option>
			<option value="1">25</option>
		</select>
	</div>

	<div class="display">
	 	<a href="<?php echo $linkList ?>" class="change-display" data-type="list"><i class="active fa fa-list"></i></a>
		<a href="<?php echo $linkGrid ?>" class="change-display" data-type="grid"><i class="fa fa-th"></i></a>
	</div>
</div>

<!-- PRODUCT GRID -->
<div class="area-content">
	<?php echo $this->list_book_category ?>
</div>

<!-- PAGINATION -->
<div class="pagination">
	<div class="results">Showing 1 to 3 of 3 (1 Pages)</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$(".change-display").removeClass("display-active");
		$(".display [data-type=<?php echo $this->displayType ?>]").addClass("display-active");
	})
</script>
