<?php 
	$pagination   = $this->paramSetting['pagination'];
	$filter       = $this->paramSetting['filter'];

	$categoryItem = $this->categoryItem;
	$this->headTitle($categoryItem->name);
	//LINK - LAYOUT
	$linkGrid     = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>"grid","page" => $pagination['curentPage'],"order" => $filter['order'],"dir" => $filter['dir']));
	$linkList     = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>"list","page" => $pagination['curentPage'],"order" => $filter['order'],"dir" => $filter['dir']));
	//LINK -FILTER - SORT
	$linkSortCurent  = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>$displayType,"page" => 1,"order" => $filter['order'],"dir" => $filter['dir']));
	$linkIdDesc      = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>$displayType,"page" => 1,"order" => "id","dir" => "desc"));
	$linkNameAsc     = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>$displayType,"page" => 1,"order" => "name","dir" => "asc"));
	$linkNameDesc    = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>$displayType,"page" => 1,"order" => "name","dir" => "desc"));
	$linkPriceAsc    = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>$displayType,"page" => 1,"order" => "price","dir" => "asc"));
	$linkPriceDesc   = $this->url("shopRoute/category",array("id"=>$categoryItem->id,"display"=>$displayType,"page" => 1,"order" => "price","dir" => "desc"));
	
?>
<!-- BREADCRUMB -->
<div class="breadcrumb">
	<?php echo $this->createBreadcrumb($listBreadcumb); ?>
</div>

<!-- CATEGORY NAME -->
<h1 class="style-1"><?php echo $categoryItem->name ?></h1>

<!-- CATEGORY INFO -->
<div class="category-info">
	<?php echo $categoryItem->description ?>
</div>

<!-- PRODUCT FILTER -->
<div class="product-filter">
	<div class="sort">
		<b>Sort By:</b> 
		
			<?php 
				echo $this->zvnFormSelectBox("filter_sort",null,array(
							$linkIdDesc    => "Mới nhất ",
							$linkNameAsc   => "Name (A - Z)",
							$linkNameDesc  => "Name (Z - A)",
							$linkPriceAsc  => "Price (A - Z)",
							$linkPriceDesc => "Price (Z - A)",						
					),$linkSortCurent); ?>
	</div>

	<div class="limit">
		<b>Show:</b> <select onchange="location = this.value;">
			<option value="1" selected="selected">6</option>
			<option value="1">25</option>
		</select>
	</div>

	<div class="display">
	 	<a href="<?php echo $linkList ?>" class="change-display" data-type="list"><i class="active fa fa-list"></i></a>
		<a href="<?php echo $linkGrid ?>" class="change-display" data-type="grid"><i class="fa fa-th"></i></a>
	</div>
</div>

<!-- PRODUCT GRID -->
<div class="area-content">
	<?php echo $this->list_book_category ?>
</div>

<!-- PAGINATION -->
<div class="pagination">
	 	<?php
	     	$realURL = $this->linkToGo("shopRoute/category",array("display"=>$displayType,"id" => $categoryItem->id,"order" => $filter['order'],"dir" => $filter['dir']));
	      	echo $this->paginationControl($this->paginator,null,"frontend_paginator.phtml",array("realURL"=>$realURL));
	    ?>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$(".change-display").removeClass("display-active");
		$(".display [data-type=<?php echo $this->displayType ?>]").addClass("display-active");

		$("select[name=filter_sort]").on("change",function(){
			var url = $(this).val();
			window.location = url;
		})
	})
</script>
