<!-- script -->
<?php 
	echo $this->headScript()->appendFile(URL_SCRIPT."ckeditor/ckeditor.js","text/javascript");
?>

<!-- BUTTON-TOOL -->
<?php echo $this->render("area_button.phtml") ?>

<?php 
	$myForm = $this->myForm;
	$myForm->prepare();	
?>

<!-- ALERT -->
<?php  echo $this->flashMessenger()->render(); ?>
<div class="box box-info">
	<?php echo $myForm->showError() ?>
    <div class="box-body">
    	<?php 
    		echo $this->form()->openTag($myForm);
	    		echo $this->partialLoop("partial_formAdminGroup.phtml",array(
	    				array("elm" =>$myForm->get("name")),
	    				array("elm" =>$myForm->get("parent")),
	    				array("elm" =>$myForm->get("status")),
	    				array("elm" =>$myForm->get("description")),
	    				array("elm" =>$myForm->get("id"),"type"=>"hidden"),
	    				array("elm" =>$myForm->get("action"),"type"=>"hidden"),	    				
	    			));
    		echo $this->form()->closeTag();
    	?>
    </div>
</div>

<script type="text/javascript">
//category
	$(document).ready(function(){
		var id = $("input[name=id]").val();
		$("select[name=parent] option[value="+id+"]").attr("disabled",true)
	})
	CKEDITOR.replace('description',{ 
        	customConfig : "custom/config_1.js",
    });
</script>