<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="box info">
	<div class="box-content">
		<div class="fb-page" data-href="https://www.facebook.com/facebook" data-width="245" data-small-header="true" data-adapt-container-width="false" data-hide-cover="false" data-show-facepile="true">
			<div class="fb-xfbml-parse-ignore">
				<blockquote cite="https://www.facebook.com/facebook">
					<a href="https://www.facebook.com/facebook">Facebook</a>
				</blockquote>
			</div>
		</div>
	</div>
</div>