<div class="col-sm-6">
			<div class="right">
				<div class="heading">
					<i class="fa fa-key"></i>
					<div class="extra-wrap">
						<h2>Returning Customer</h2>
						<b>I am a returning customer</b>
					</div>
				</div>

				<?php 
					echo $this->view->form()->openTag($formElement);

				?>

					<div class="content">
						<?php echo $formElement->showError(); ?>
						<?php echo $authError ?>
						<div class="form-group">
							<?php echo $this->view->formLabel($formElement->get('email')) ?>
							<div class="controls col-sm-7">
								<?php echo $this->view->formInput($formElement->get('email')) ?>
							</div>
						</div>
						<div class="form-group">
							<?php echo $this->view->formLabel($formElement->get('password')) ?>
							<div class="controls col-sm-7">
								<?php echo $this->view->formInput($formElement->get('password')) ?>
							</div>
									<!-- <span class="error help-inline">First Name must be between 1 and 32 characters!</span> -->
						</div>
						<div class="login-buttons">
							<a onclick="$('#login').submit();" class="button-cont-right">Login<i class="fa fa-arrow-circle-right"></i></a> 
							<a class="link-login" href="#">Forgotten Password</a>
						</div>
					</div>
				<?php
					echo $this->view->form()->closeTag();
				?>
			</div>
		</div>