<div class="col-sm-6">
	<div class="left">
		<div class="heading">
			<i class="fa fa-file-text-o"></i>
			<div class="extra-wrap">
				<h2>CHƯA CÓ TÀI KHOẢN</h2>
				<b>Đăng ký tài khoàn</b>
			</div>
		</div>
		<div class="content">
			<p>By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.</p>
			<a href="<?php echo $this->view->url('shopRoute/default',array('controller'=>'index','action'=>'register')) ?>" class="button-cont-right">Continue<i class="fa fa-arrow-circle-right"></i></a>
		</div>
	</div>
</div>