<?php 
	if(!empty($this->_data)){
		$img       =  URL_FILES."books/thumb/140x210/" . $this->_data->picture;
		$name      = $this->_data->name;
		$realPrice = $this->view->createPrice($this->_data->price,$this->_data->sale_off,array("task"=>"book-special"));
		$link      = $this->view->url("shopRoute/default",array("controller" => "book","action" => "popup"));
	}
 ?>

<div class="box specials">
	<div class="box-heading special-heading">Specials</div>
	<div class="box-content">
		<div class="box-product">
			<ul class="row">
				<li class="first-in-line col-sm-4">
					<div class="padding">
						<div class="image2">
							<a href="#">
								<img id="img_43" src="<?php echo $img ?>"alt="<?php echo $name ?> " />
							</a>
						</div>
						
						<!-- SHOW POPUP -->
						<a href="<?php echo $link ?>" data-id="<?php echo $this->_data->id ?>" class="colorbox quick-view-button"><i class=" fa fa-search "></i></a>
						
						<div class="inner">
							<div class="f-left">
								<div class="price">
									<?php echo $realPrice ?>
								</div>
								<div class="name maxheight-spec">
									<a href="#"><?php echo $name ?></a>
								</div>
							</div>
							
							<div class="cart-button">
								<div class="cart">
									<a title="Add to cart" data-id="43;" class="button addToCart">
										<span>Add to cart</span>
									</a>
								</div>
								<span class="clear"></span>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
				</li>
			</ul>
		</div>
	</div>
</div>

<div style="display: none;">
	<div class="quick-view preview">

	</div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	// SHOW POPUP
	$("a.colorbox").click(function(){
		var url  = $(this).attr("href");
		var o_id = $(this).data("id");
		$(".quick-view").load(url,{id:o_id});
		$("a.colorbox").colorbox({
			rel: 'colorbox1',
			inline:true,
			html: true,
			width:'58%',
			maxWidth:'780px',
			height:'70%',
			open:false,
			returnFocus:false,
			fixed: true,
			title: false,
			href:'.quick-view',
		});	
	})
})
</script>