<?php echo  $this->doctype() ?>
<html>

<head>

	<?php 
		//title
		echo $this->headTitle()->append("frontend") ;
		//meta
		echo $this->headMeta()->appendName("viewport","width=device-width, initial-scale=1")
		                      ->appendName("description","Trongle no1")
		                      ->setCharset("utf-8");	
	?>
	
	
</head>
<body>
	
	<div class="container">
		<?php echo $this->content ?>
	</div>
</body>
</html>