<div class="box featured">
	<div class="box-heading">Featured</div>
	<div class="box-content">
		<div class="box-product">
			<ul class="row">
				<li class="first-in-line col-sm-4">
					<div class="padding">
						<div class="image2">
							<a href="#"><img id="img_32"
								src="<?php echo URL_IMG_SHOP ?>data/product-04-190x190.png"
								alt="Lorem ipsum dolor sit amet conse ctetur adipisicing elit sed do eiusmod tempor" /></a>
						</div>

						<a href="#" class="colorbox1 quick-view-button"><i
							class=" fa fa-search "></i></a>
						<div class="inner">
							<div class="f-left">
								<div class="price">$119.50</div>
								<div class="name maxheight-feat">
									<a href="#">Lorem ipsum dolor sit amet conse ctetur adipisicing
										elit sed do eiusmod tempor</a>
								</div>
							</div>
							<div class="cart-button">
								<div class="cart">
									<a title="Add to cart" data-id="32;" class="button addToCart"><span>Add
											to cart</span></a>
								</div>
								<span class="clear"></span>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>

				</li>

				<li class=" col-sm-4">
					<div class="padding">
						<div class="image2">
							<a href="#"><img id="img_29"
								src="<?php echo URL_IMG_SHOP ?>data/product-07-190x190.png"
								alt="Ut enim ad minim veniam, quis nostrud exercitationmodo " /></a>
						</div>

						<a href="#" class="colorbox2 quick-view-button"><i
							class=" fa fa-search "></i></a>
						<div class="inner">
							<div class="f-left">
								<div class="price">$330.99</div>
								<div class="name maxheight-feat">
									<a href="#">Ut enim ad minim veniam, quis nostrud
										exercitationmodo </a>
								</div>
							</div>
							<div class="cart-button">
								<div class="cart">
									<a title="Add to cart" data-id="29;" class="button addToCart">
										<span>Add to cart</span>
									</a>
								</div>
								<span class="clear"></span>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
				</li>
				<li class="last-in-line col-sm-4">
					<div class="padding">
						<div class="image2">
							<a href="#"><img id="img_36"
								src="<?php echo URL_IMG_SHOP ?>data/product-16-190x190.png"
								alt="Ullamco laboris nisi ut aliquip ex ea com" /></a>
						</div>

						<a href="#" class="colorbox3 quick-view-button"><i
							class=" fa fa-search "></i></a>
						<div class="inner">
							<div class="f-left">
								<div class="price">$119.50</div>
								<div class="name maxheight-feat">
									<a href="#">Ullamco laboris nisi ut aliquip ex ea com</a>
								</div>
							</div>
							<div class="cart-button">
								<div class="cart">
									<a title="Add to cart" data-id="36;" class="button addToCart">
										<span>Add to cart</span>
									</a>
								</div>
								<span class="clear"></span>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
				</li>



				<li class="first-in-line last_line col-sm-4">
					<div class="padding">
						<div class="image2">
							<a href="#"><img id="img_34"
								src="<?php echo URL_IMG_SHOP ?>data/product-31-190x190.png"
								alt="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt " /></a>
						</div>

						<a href="#" class="colorbox7 quick-view-button"><i
							class=" fa fa-search "></i></a>
						<div class="inner">
							<div class="f-left">
								<div class="price">$119.50</div>
								<div class="name maxheight-feat">
									<a href="#">Excepteur sint occaecat cupidatat non proident,
										sunt in culpa qui officia deserunt </a>
								</div>
							</div>
							<div class="cart-button">
								<div class="cart">
									<a title="Add to cart" data-id="34;" class="button addToCart">
										<span>Add to cart</span>
									</a>
								</div>
								<span class="clear"></span>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
				</li>
				<li class=" last_line col-sm-4">
					<div class="padding">
						<div class="image2">
							<a href="#"><img id="img_47"
								src="<?php echo URL_IMG_SHOP ?>data/product-37-190x190.png"
								alt="Ipsum dolor conse" /></a>
						</div>

						<a href="#" class="colorbox8 quick-view-button"><i
							class=" fa fa-search "></i></a>
						<div class="inner">
							<div class="f-left">
								<div class="price">$119.50</div>
								<div class="name maxheight-feat">
									<a href="#">Ipsum dolor conse</a>
								</div>
							</div>
							<div class="cart-button">
								<div class="cart">
									<a title="Add to cart" data-id="47;" class="button addToCart">
										<span>Add to cart</span>
									</a>
								</div>
								<span class="clear"></span>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
				</li>
				<li class="last-in-line last_line col-sm-4">
					<div class="padding">
						<div class="image2">
							<a href="#"><img id="img_48"
								src="<?php echo URL_IMG_SHOP ?>data/product-55-190x190.png"
								alt="Ut labore et Ut labore et" /></a>
						</div>

						<a href="#" class="colorbox9 quick-view-button"><i
							class=" fa fa-search "></i></a>
						<div class="inner">
							<div class="f-left">
								<div class="price">$119.50</div>
								<div class="name maxheight-feat">
									<a href="#">Ut labore et Ut labore et</a>
								</div>
							</div>
							<div class="cart-button">
								<div class="cart">
									<a title="Add to cart" data-id="48;" class="button addToCart">
										<span>Add to cart</span>
									</a>
								</div>
								<span class="clear"></span>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
				</li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</div>