<?php 
  $contentBoxes =[
    ["class" =>"bg-aqua","text-1"=>"150","text-2"=>"New Orders","icon"=>"ion-bag","link"=>"#"],
    ["class" =>"bg-green","text-1"=>"53<sup style='font-size: 20px'>%</sup>","text-2"=>"Bounce Rate","icon"=>"ion-stats-bars","link"=>"#"],
    ["class" =>"bg-yellow","text-1"=>"44","text-2"=>"User Registrations","icon"=>"ion-person-add","link"=>"#"],
    ["class" =>"bg-red","text-1"=>"65","text-2"=>"Unique Visitors","icon"=>"ion-pie-graph","link"=>"#"]
  ];

  $xhtmlBoxes = "<div class='row'>";
  foreach($contentBoxes as $content){
    $xhtmlBoxes .= sprintf('<div class="col-lg-3 col-xs-6"> 
                                <div class="small-box %s">
                                  <div class="inner">
                                    <h3>%s</h3>
                                    <p>%s</p>
                                  </div>
                                  <div class="icon">
                                    <i class="ion %s"></i>
                                  </div>
                                  <a href="%s" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                                </div>
                              </div>',
                            $content['class'],
                            $content['text-1'],
                            $content['text-2'],
                            $content['icon'],
                            $content['link']);
  }
  $xhtmlBoxes .= "</div>";
?>
<?php 
    echo $xhtmlBoxes;
?>
    

            
            
