<!-- BUTTON-TOOL -->
<div class="text-center">
<?php
	$currentAction = $this->layout()->params['action'];
	switch ($currentAction) {
		case 'index':
			echo $this->buttonTool("Ordering","fa-repeat","ordering");
			echo $this->buttonTool("Add","fa-plus-square-o",null,"no","/admin/group/add");
			echo $this->buttonTool("Active","fa-check-circle-o","active");
			echo $this->buttonTool("InActive","fa-circle-o","inactive");
			echo $this->buttonTool("Delete","fa-minus-circle","delete");
			break;
		case 'add':
		case 'edit':
			echo $this->buttonTool("Save","fa-save","submit","no");
			echo $this->buttonTool("Cancel","fa-arrow-circle-left",null,"no","/admin/group/index");
			break;
		default:
			break;
	}
?>
</div>