<div class="col-xs-4">
    <div class="dataTables_filter" id="example1_filter" style="float: left;">
      <div class="input-group input-group-sm">
          <div class="input-group-btn">
              <?php echo $this->keyword_type ?>
          </div>
              <?php echo $this->keyword_text ?>
          <span class="input-group-btn">
              <?php echo $this->button ?>
          </span>
      </div>
    </div>
</div>
